import time
from CommonClass.web_utils.CommonActions import click, send_keys


class Create_Member():
    def __init__(self, uiTestData):
        self.uiTestData = uiTestData


    def create_Member_id(self):
        click(self.uiTestData['locators']['member_search_id'])
        time.sleep(1)
        click(self.uiTestData['locators']['member_xpath'])
        time.sleep(1)
        click(self.uiTestData['locators']['member_new_member_xpath'])
        time.sleep(1)
        send_keys(self.uiTestData['locators']['member_first_name_xpath'], self.uiTestData['member']['first_name'])
        time.sleep(2)
        send_keys(self.uiTestData['locators']['member_last_name_xpath'], self.uiTestData['member']['last_name'])
        time.sleep(2)
        send_keys(self.uiTestData['locators']['create_member_id_xpath'], self.uiTestData['member']['create_member_id'])
        time.sleep(2)
        click(self.uiTestData['locators']['click_client_code'])
        time.sleep(2)
        click(self.uiTestData['client']['client_code'])
        time.sleep(2)
        send_keys(self.uiTestData['locators']['member_dob_xpath'], self.uiTestData['member']['DOB'])
        time.sleep(2)
        click(self.uiTestData['locators']['member_click_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['member_save_exit_xpath'])
        time.sleep(1)
        print("Member created successfully")
        send_keys(self.uiTestData['locators']['enrollment_member_search_id'], self.uiTestData['member']['search_Member_ID'])
        time.sleep(2)
        click(self.uiTestData['locators']['enrollment_member_search_button'])
        time.sleep(2)
        click(self.uiTestData['locators']['enrollment_member_click_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['create_new_enrollment_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['enrollment_edit_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['enrollment_add_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['enrollment_this_member_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['enrollment_relationship_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['enrollment_relationship_type_xpath'])
        time.sleep(2)
        send_keys(self.uiTestData['locators']['enrollment_date_xpath'], self.uiTestData['member']['Enrollment_date'])
        time.sleep(2)
        click(self.uiTestData['locators']['click_enrollment_lob'])
        time.sleep(2)
        click(self.uiTestData['enrollment']['enter_enrollment_lob'])
        time.sleep(2)
        send_keys(self.uiTestData['locators']['click_enrollment_plan'], self.uiTestData['enrollment']['Enrollment_plan'])
        time.sleep(2)
        click(self.uiTestData['locators']['enrollment_save_exit_button_xpath'])
        time.sleep(3)
        print("Enrollment create successfully")