import locator


class Locators():
    def __init__(self):
        self.uiTestData = None


    def test_locators(self):
        member_search_id = "//*[@id='commandBarForm=searchButton']",
        member_xpath = "//*[@class='ui-menuitem-text' and text()='Members']",
        member_new_member_xpath = "//*[@class='ui-button-text ui-c' and text()='New Member']",
        member_first_name_xpath = "//*[@name='memberDetailIdentificationForm=firstname']",
        member_last_name_xpath = "//*[@name='memberDetailIdentificationForm=lastName']",
        create_member_id_xpath = "//*[@name='memberDetailIdentificationForm=memberId']",
        click_client_code = "//*[@id='memberDetailIdentificationForm=j_idt95_label']",
        member_dob_xpath = "//*[@name='memberDetailIdentificationForm=birthDate_input']",
        member_click_xpath = "(//*[@class='ui-radiobutton-icon ui-icon ui-icon-blank ui-c'])[1]",
        member_save_exit_xpath = "//*[@class='ui-button-text ui-c' and text()='Save & Exit']",
        enrollment_member_search_id = "//*[@id='memberSearchTabView=memberIdSearchForm=memberId']",
        enrollment_member_search_button = "//*[@id='memberSearchTabView=memberIdSearchForm=memberIdSearchLocalButton']",
        enrollment_member_click_xpath = "(//*[@class='ui-commandlink ui-widget'])[2]",
        create_new_enrollment_xpath = "//*[@class='ui-menuitem-text' and text()='Enrollment']",
        enrollment_edit_xpath = "//*[@class='ui-button-text ui-c' and text()='Edit']",
        enrollment_add_xpath = "//*[@class='ui-button-text ui-c' and text()='Add']",
        enrollment_this_member_xpath = "(//*[@class='ui-radiobutton-icon ui-icon ui-icon-blank ui-c'])[1]",
        enrollment_relationship_xpath = "//*[@id='memberDetailEnrollmentForm=member_Relationship_label']",
        enrollment_relationship_type_xpath = "//*[@data-label='Cousin']",
        enrollment_date_xpath = "//*[@name='memberDetailEnrollmentForm=effDate_input']",
        click_enrollment_lob = "//*[@id='memberDetailEnrollmentForm=member_lob_label']",
        click_enrollment_plan = "//*[@id='memberDetailEnrollmentForm=member_plan_input']",
        enrollment_save_exit_button_xpath = "//*[@class='ui-button-text ui-c' and text()='Save & Exit']",
        member_search_button_xpath = "//*[@id='memberSearchResultsForm=memberSearchResultsTable=searchResultsTable=0=memberSearchGotoCMV']",
        create_new_request_xpath = "//*[@class='ui-menuitem-text' and text()='New Program/Request']",
        request_medical_inpatient_xpath = "//*[@class='ui-menuitem-text' and text()='Medical Inpatient']",
        request_treatment_setting_xpath = "//*[@id='requestForm=treatmentSetting_label']",
        request_treatment_inpatient_xpath = "//*[@data-label='Inpatient']",
        request_treatment_type_xpath = "//*[@id='requestForm=treatmentType_label']",
        request_treatment_type_medical_xpath = "//*[@data-label='Medical']",
        request_review_type_xpath = "// label[@id='requestForm=reviewType_label']",
        request_days_xpath = "//li[text()='10BusinessDays']",
        request_days_xpath_6 = "//li[text()='10 Business Days']",
        request_admit_date_xpath = "(//*[@class='ui-inputfield ui-widget ui-state-default ui-corner-all hasDatepicker'])[1]",
        click_request_unit_xpath = "//*[@name='requestForm=requestedUnits']",
        enter_request_unit_xpath = "//*[@name='requestForm=requestedUnits']",
        click_request_urgency_xpath = "(//*[@class='ui-icon ui-icon-triangle-1-s ui-c'])[5]",
        enter_request_emergency_xpath = "//*[@data-label='Emergency']",
        click_save_exit_xpath = "//*[@class='ui-button-text ui-c' and text()='Save & Exit']",
        click_aerial_xpath = "//a[@title='Home']",
        click_inpatient_button = "//*[@title='Inpatient']",
        click_add_new_item_button = "//*[@class='ui-button-text ui-c' and text()='Add New Item']",
        create_task_button = "//*[@class='ui-menuitem-text' and text()='Task']",
        click_task_type = "//*[@id='addTask=taskForm=taskType_label']",
        enter_add_attachment = "//*[@data-label='Add Attachment']",
        click_task_reason = "//label[@class='ui-selectonemenu-label ui-inputfield ui-corner-all' and @id='addTask=taskForm=taskReason_label']",
        enter_task_reason_exchange = "//li[@data-label='Add Attachment in iExchange']",
        click_priority_button = "//*[@id='addTask=taskForm=priority_label']",
        click_and_enter_priority = "//*[@data-label='Urgent']",
        click_save_exit_button = "(//*[@class='ui-button-text ui-c' and text() ='Save & Exit'])[2]",
