import time
from CommonClass.web_utils.CommonActions import click, send_keys


class Member():
    def __init__(self, uiTestData):
        self.uiTestData = uiTestData


    def create_Member(self):
        click(self.uiTestData['locators']['member_search_id'])
        time.sleep(1)
        click(self.uiTestData['locators']['member_xpath'])
        time.sleep(1)
        click(self.uiTestData['locators']['member_new_member_xpath'])
        time.sleep(1)
        send_keys(self.uiTestData['locators']['member_first_name_xpath'], self.uiTestData['member']['first_name'])
        time.sleep(2)
        send_keys(self.uiTestData['locators']['member_last_name_xpath'], self.uiTestData['member']['last_name'])
        time.sleep(2)
        send_keys(self.uiTestData['locators']['create_member_id_xpath'], self.uiTestData['member']['create_member_id'])
        time.sleep(2)
        click(self.uiTestData['locators']['click_client_code'])
        time.sleep(2)
        click(self.uiTestData['client']['client_code'])
        time.sleep(2)
        send_keys(self.uiTestData['locators']['member_dob_xpath'], self.uiTestData['member']['DOB'])
        time.sleep(2)
        click(self.uiTestData['locators']['member_click_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['member_save_exit_xpath'])
        time.sleep(1)
        print("Member created successfully")
        send_keys(self.uiTestData['locators']['enrollment_member_search_id'], self.uiTestData['member']['search_Member_ID'])
        time.sleep(2)
        click(self.uiTestData['locators']['enrollment_member_search_button'])
        time.sleep(2)
        click(self.uiTestData['locators']['enrollment_member_click_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['create_new_enrollment_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['enrollment_edit_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['enrollment_add_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['enrollment_this_member_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['enrollment_relationship_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['enrollment_relationship_type_xpath'])
        time.sleep(2)
        send_keys(self.uiTestData['locators']['enrollment_date_xpath'], self.uiTestData['member']['Enrollment_date'])
        time.sleep(2)
        click(self.uiTestData['locators']['click_enrollment_lob'])
        time.sleep(2)
        click(self.uiTestData['enrollment']['enter_enrollment_lob'])
        time.sleep(2)
        send_keys(self.uiTestData['locators']['click_enrollment_plan'], self.uiTestData['enrollment']['Enrollment_plan'])
        time.sleep(2)
        click(self.uiTestData['locators']['enrollment_save_exit_button_xpath'])
        time.sleep(3)
        print("Enrollment create successfully")
        click(self.uiTestData['locators']['member_search_id'])
        time.sleep(2)
        click(self.uiTestData['locators']['member_xpath'])
        time.sleep(2)
        # self.enrollment_member_search_id).send_keys(self.uiTestData['member']['search_Member_ID'])
        click(self.uiTestData['locators']['enrollment_member_search_button'])
        time.sleep(2)
        click(self.uiTestData['locators']['member_search_button_xpath'])
        time.sleep(5)
        print("Member Id search successfully")
        click(self.uiTestData['locators']['create_new_request_xpath'])
        time.sleep(1)
        click(self.uiTestData['locators']['request_medical_inpatient_xpath'])
        time.sleep(1)
        click(self.uiTestData['locators']['request_treatment_setting_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['request_treatment_inpatient_xpath'])
        time.sleep(1)
        click(self.uiTestData['locators']['request_treatment_type_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['request_treatment_type_medical_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['request_review_type_xpath'])
        time.sleep(3)
        # click(self.uiTestData['locators']['request_days_xpath'])
        # time.sleep(2)
        click(self.uiTestData['locators']['request_days_xpath_6'])
        time.sleep(2)
        send_keys(self.uiTestData['locators']['request_admit_date_xpath'], self.uiTestData['request']['Request_date'])
        time.sleep(2)
        click(self.uiTestData['locators']['click_request_unit_xpath'])
        time.sleep(1)
        send_keys(self.uiTestData['locators']['enter_request_unit_xpath'], self.uiTestData['request']['Request_units'])
        time.sleep(2)
        click(self.uiTestData['locators']['click_request_urgency_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['enter_request_emergency_xpath'])
        time.sleep(2)
        click(self.uiTestData['locators']['click_save_exit_xpath'])
        time.sleep(3)
        click(self.uiTestData['locators']['click_aerial_xpath'])
        time.sleep(1)
        click(self.uiTestData['locators']['member_search_id'])
        time.sleep(1)
        click(self.uiTestData['locators']['member_xpath'])
        time.sleep(1)
        click(self.uiTestData['locators']['enrollment_member_search_button'])
        time.sleep(1)
        click(self.uiTestData['locators']['member_search_button_xpath'])
        time.sleep(2)
        print("Request created successfully ")
        print("Request Was Created by Given Member ID : ", self.uiTestData['member']['search_Member_ID'])
        click(self.uiTestData['locators']['click_inpatient_button'])
        time.sleep(1)
        click(self.uiTestData['locators']['click_add_new_item_button'])
        time.sleep(2)
        click(self.uiTestData['locators']['create_task_button'])
        time.sleep(3)
        click(self.uiTestData['locators']['click_task_type'])
        time.sleep(2)
        click(self.uiTestData['locators']['enter_add_attachment'])
        time.sleep(2)
        click(self.uiTestData['locators']['click_task_reason'])
        time.sleep(3)
        click(self.uiTestData['locators']['enter_task_reason_exchange'])
        time.sleep(2)
        click(self.uiTestData['locators']['click_priority_button'])
        time.sleep(2)
        click(self.uiTestData['locators']['click_and_enter_priority'])
        time.sleep(2)
        click(self.uiTestData['locators']['click_save_exit_button'])
        time.sleep(2)
        print("Task created successfully")
        print("Task Was Created by Given Member ID : ", self.uiTestData['member']['search_Member_ID'])
